// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.6.1
// source: idl/user/user.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"user_name" form:"user_name" uri:"user_name"
	UserName string `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	// @inject_tag: json:"password" form:"password" uri:"password"
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	// @inject_tag: json:"password_confirm" form:"password_confirm" uri:"password_confirm"
	// confirm when register user
	PasswordConfirm string `protobuf:"bytes,3,opt,name=PasswordConfirm,proto3" json:"PasswordConfirm,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_idl_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_idl_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetPasswordConfirm() string {
	if x != nil {
		return x.PasswordConfirm
	}
	return ""
}

type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"user_name" form:"user_name" uri:"user_name"
	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	// @inject_tag: json:"password" form:"password" uri:"password"
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_idl_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_idl_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"user_id" form:"user_id" uri:"user_id"
	UserId int64 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	// @inject_tag: json:"user_name" form:"user_name" uri:"user_name"
	UserName      string `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_idl_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_idl_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type UserDetailResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"code" form:"code"" uri:"code""
	Code int64 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	// @inject_tag: json:"user_response" form:"user_response" uri:"user_response"
	UserDetail    *UserResponse `protobuf:"bytes,2,opt,name=UserDetail,proto3" json:"UserDetail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDetailResponse) Reset() {
	*x = UserDetailResponse{}
	mi := &file_idl_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetailResponse) ProtoMessage() {}

func (x *UserDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetailResponse.ProtoReflect.Descriptor instead.
func (*UserDetailResponse) Descriptor() ([]byte, []int) {
	return file_idl_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserDetailResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserDetailResponse) GetUserDetail() *UserResponse {
	if x != nil {
		return x.UserDetail
	}
	return nil
}

// using token to verify when logout
type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_idl_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_idl_user_user_proto_rawDescGZIP(), []int{4}
}

type UserCommonResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"code" form:"code"" uri:"code""
	Code int64 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	// @inject_tag: json:"msg" form:"msg"" uri:"msg""
	Msg string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	// @inject_tag: json:"data" form:"data"" uri:"data""
	Data          string `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCommonResponse) Reset() {
	*x = UserCommonResponse{}
	mi := &file_idl_user_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCommonResponse) ProtoMessage() {}

func (x *UserCommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_user_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCommonResponse.ProtoReflect.Descriptor instead.
func (*UserCommonResponse) Descriptor() ([]byte, []int) {
	return file_idl_user_user_proto_rawDescGZIP(), []int{5}
}

func (x *UserCommonResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserCommonResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *UserCommonResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_idl_user_user_proto protoreflect.FileDescriptor

const file_idl_user_user_proto_rawDesc = "" +
	"\n" +
	"\x13idl/user/user.proto\"s\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\bUserName\x18\x01 \x01(\tR\bUserName\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\x12(\n" +
	"\x0fPasswordConfirm\x18\x03 \x01(\tR\x0fPasswordConfirm\"G\n" +
	"\fLoginRequest\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"B\n" +
	"\fUserResponse\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x1a\n" +
	"\bUserName\x18\x02 \x01(\tR\bUserName\"W\n" +
	"\x12UserDetailResponse\x12\x12\n" +
	"\x04Code\x18\x01 \x01(\x03R\x04Code\x12-\n" +
	"\n" +
	"UserDetail\x18\x02 \x01(\v2\r.UserResponseR\n" +
	"UserDetail\"\x0f\n" +
	"\rLogoutRequest\"N\n" +
	"\x12UserCommonResponse\x12\x12\n" +
	"\x04Code\x18\x01 \x01(\x03R\x04Code\x12\x10\n" +
	"\x03Msg\x18\x02 \x01(\tR\x03Msg\x12\x12\n" +
	"\x04Data\x18\x03 \x01(\tR\x04Data2\xa8\x01\n" +
	"\vUserService\x12/\n" +
	"\tUserLogin\x12\r.LoginRequest\x1a\x13.UserDetailResponse\x125\n" +
	"\fUserRegister\x12\x10.RegisterRequest\x1a\x13.UserCommonResponse\x121\n" +
	"\n" +
	"UserLogout\x12\x0e.LogoutRequest\x1a\x13.UserCommonResponseB-Z+github.com/lukkaal/GRPC-API/idl/user;userpbb\x06proto3"

var (
	file_idl_user_user_proto_rawDescOnce sync.Once
	file_idl_user_user_proto_rawDescData []byte
)

func file_idl_user_user_proto_rawDescGZIP() []byte {
	file_idl_user_user_proto_rawDescOnce.Do(func() {
		file_idl_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_idl_user_user_proto_rawDesc), len(file_idl_user_user_proto_rawDesc)))
	})
	return file_idl_user_user_proto_rawDescData
}

var file_idl_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_idl_user_user_proto_goTypes = []any{
	(*RegisterRequest)(nil),    // 0: RegisterRequest
	(*LoginRequest)(nil),       // 1: LoginRequest
	(*UserResponse)(nil),       // 2: UserResponse
	(*UserDetailResponse)(nil), // 3: UserDetailResponse
	(*LogoutRequest)(nil),      // 4: LogoutRequest
	(*UserCommonResponse)(nil), // 5: UserCommonResponse
}
var file_idl_user_user_proto_depIdxs = []int32{
	2, // 0: UserDetailResponse.UserDetail:type_name -> UserResponse
	1, // 1: UserService.UserLogin:input_type -> LoginRequest
	0, // 2: UserService.UserRegister:input_type -> RegisterRequest
	4, // 3: UserService.UserLogout:input_type -> LogoutRequest
	3, // 4: UserService.UserLogin:output_type -> UserDetailResponse
	5, // 5: UserService.UserRegister:output_type -> UserCommonResponse
	5, // 6: UserService.UserLogout:output_type -> UserCommonResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_idl_user_user_proto_init() }
func file_idl_user_user_proto_init() {
	if File_idl_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_idl_user_user_proto_rawDesc), len(file_idl_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_user_user_proto_goTypes,
		DependencyIndexes: file_idl_user_user_proto_depIdxs,
		MessageInfos:      file_idl_user_user_proto_msgTypes,
	}.Build()
	File_idl_user_user_proto = out.File
	file_idl_user_user_proto_goTypes = nil
	file_idl_user_user_proto_depIdxs = nil
}
