// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.6.1
// source: idl/task/task.proto

package taskpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ----------------- Task Model -----------------
type TaskModel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"task_id" form:"task_id"
	TaskId int64 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// @inject_tag: json:"user_id" form:"user_id"
	UserId int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// @inject_tag: json:"status" form:"status"
	Status int64 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	// @inject_tag: json:"title" form:"title"
	Title string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	// @inject_tag: json:"content" form:"content"
	Content string `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	// @inject_tag: json:"start_time" form:"start_time"
	StartTime int64 `protobuf:"varint,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// @inject_tag: json:"end_time" form:"end_time"
	EndTime       int64 `protobuf:"varint,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskModel) Reset() {
	*x = TaskModel{}
	mi := &file_idl_task_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskModel) ProtoMessage() {}

func (x *TaskModel) ProtoReflect() protoreflect.Message {
	mi := &file_idl_task_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskModel.ProtoReflect.Descriptor instead.
func (*TaskModel) Descriptor() ([]byte, []int) {
	return file_idl_task_task_proto_rawDescGZIP(), []int{0}
}

func (x *TaskModel) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskModel) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TaskModel) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TaskModel) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TaskModel) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TaskModel) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *TaskModel) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

// ----------------- Task Requests -----------------
type TaskCreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"user_id" form:"user_id"
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// @inject_tag: json:"title" form:"title"
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// @inject_tag: json:"content" form:"content"
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// @inject_tag: json:"start_time" form:"start_time"
	StartTime int64 `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// @inject_tag: json:"end_time" form:"end_time"
	EndTime int64 `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// @inject_tag: json:"status" form:"status"
	Status        int64 `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCreateRequest) Reset() {
	*x = TaskCreateRequest{}
	mi := &file_idl_task_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCreateRequest) ProtoMessage() {}

func (x *TaskCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_task_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCreateRequest.ProtoReflect.Descriptor instead.
func (*TaskCreateRequest) Descriptor() ([]byte, []int) {
	return file_idl_task_task_proto_rawDescGZIP(), []int{1}
}

func (x *TaskCreateRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TaskCreateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TaskCreateRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TaskCreateRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *TaskCreateRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *TaskCreateRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type TaskUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"task_id" form:"task_id"
	TaskId int64 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // compulsory
	// @inject_tag: json:"title" form:"title"
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// @inject_tag: json:"content" form:"content"
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// @inject_tag: json:"start_time" form:"start_time"
	StartTime int64 `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// @inject_tag: json:"end_time" form:"end_time"
	EndTime int64 `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// @inject_tag: json:"status" form:"status"
	Status int64 `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	// @inject_tag: json:"user_id" form:"user_id"
	UserId        int64 `protobuf:"varint,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // compulsory
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskUpdateRequest) Reset() {
	*x = TaskUpdateRequest{}
	mi := &file_idl_task_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskUpdateRequest) ProtoMessage() {}

func (x *TaskUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_task_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskUpdateRequest.ProtoReflect.Descriptor instead.
func (*TaskUpdateRequest) Descriptor() ([]byte, []int) {
	return file_idl_task_task_proto_rawDescGZIP(), []int{2}
}

func (x *TaskUpdateRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskUpdateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TaskUpdateRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TaskUpdateRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *TaskUpdateRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *TaskUpdateRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TaskUpdateRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type TaskShowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"task_id" form:"task_id"s
	UserId        int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // compulsory
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskShowRequest) Reset() {
	*x = TaskShowRequest{}
	mi := &file_idl_task_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskShowRequest) ProtoMessage() {}

func (x *TaskShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_task_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskShowRequest.ProtoReflect.Descriptor instead.
func (*TaskShowRequest) Descriptor() ([]byte, []int) {
	return file_idl_task_task_proto_rawDescGZIP(), []int{3}
}

func (x *TaskShowRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type TaskDeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"task_id" form:"task_id"
	TaskId        int64 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // compulsory
	UserId        int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // compulsory
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskDeleteRequest) Reset() {
	*x = TaskDeleteRequest{}
	mi := &file_idl_task_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDeleteRequest) ProtoMessage() {}

func (x *TaskDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_task_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDeleteRequest.ProtoReflect.Descriptor instead.
func (*TaskDeleteRequest) Descriptor() ([]byte, []int) {
	return file_idl_task_task_proto_rawDescGZIP(), []int{4}
}

func (x *TaskDeleteRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskDeleteRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// ----------------- Task Responses -----------------
type TaskCommonResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"code" form:"code"
	Code int64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// @inject_tag: json:"msg" form:"msg"
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	// @inject_tag: json:"data" form:"data"
	Data          string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCommonResponse) Reset() {
	*x = TaskCommonResponse{}
	mi := &file_idl_task_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCommonResponse) ProtoMessage() {}

func (x *TaskCommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_task_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCommonResponse.ProtoReflect.Descriptor instead.
func (*TaskCommonResponse) Descriptor() ([]byte, []int) {
	return file_idl_task_task_proto_rawDescGZIP(), []int{5}
}

func (x *TaskCommonResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TaskCommonResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *TaskCommonResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type TasksDetailResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"code" form:"code"
	Code int64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// @inject_tag: json:"task_detail" form:"task_detail"
	TaskDetail    []*TaskModel `protobuf:"bytes,2,rep,name=task_detail,json=taskDetail,proto3" json:"task_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TasksDetailResponse) Reset() {
	*x = TasksDetailResponse{}
	mi := &file_idl_task_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TasksDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TasksDetailResponse) ProtoMessage() {}

func (x *TasksDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_task_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TasksDetailResponse.ProtoReflect.Descriptor instead.
func (*TasksDetailResponse) Descriptor() ([]byte, []int) {
	return file_idl_task_task_proto_rawDescGZIP(), []int{6}
}

func (x *TasksDetailResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TasksDetailResponse) GetTaskDetail() []*TaskModel {
	if x != nil {
		return x.TaskDetail
	}
	return nil
}

var File_idl_task_task_proto protoreflect.FileDescriptor

const file_idl_task_task_proto_rawDesc = "" +
	"\n" +
	"\x13idl/task/task.proto\"\xbf\x01\n" +
	"\tTaskModel\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x03R\x06status\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\a \x01(\x03R\aendTime\"\xae\x01\n" +
	"\x11TaskCreateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x03R\x06status\"\xc7\x01\n" +
	"\x11TaskUpdateRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x03R\x06status\x12\x17\n" +
	"\auser_id\x18\a \x01(\x03R\x06userId\"*\n" +
	"\x0fTaskShowRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"E\n" +
	"\x11TaskDeleteRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"N\n" +
	"\x12TaskCommonResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\"V\n" +
	"\x13TasksDetailResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12+\n" +
	"\vtask_detail\x18\x02 \x03(\v2\n" +
	".TaskModelR\n" +
	"taskDetail2\xe6\x01\n" +
	"\vTaskService\x125\n" +
	"\n" +
	"TaskCreate\x12\x12.TaskCreateRequest\x1a\x13.TaskCommonResponse\x125\n" +
	"\n" +
	"TaskUpdate\x12\x12.TaskUpdateRequest\x1a\x13.TaskCommonResponse\x122\n" +
	"\bTaskShow\x12\x10.TaskShowRequest\x1a\x14.TasksDetailResponse\x125\n" +
	"\n" +
	"TaskDelete\x12\x12.TaskDeleteRequest\x1a\x13.TaskCommonResponseB-Z+github.com/lukkaal/GRPC-API/idl/task;taskpbb\x06proto3"

var (
	file_idl_task_task_proto_rawDescOnce sync.Once
	file_idl_task_task_proto_rawDescData []byte
)

func file_idl_task_task_proto_rawDescGZIP() []byte {
	file_idl_task_task_proto_rawDescOnce.Do(func() {
		file_idl_task_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_idl_task_task_proto_rawDesc), len(file_idl_task_task_proto_rawDesc)))
	})
	return file_idl_task_task_proto_rawDescData
}

var file_idl_task_task_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_idl_task_task_proto_goTypes = []any{
	(*TaskModel)(nil),           // 0: TaskModel
	(*TaskCreateRequest)(nil),   // 1: TaskCreateRequest
	(*TaskUpdateRequest)(nil),   // 2: TaskUpdateRequest
	(*TaskShowRequest)(nil),     // 3: TaskShowRequest
	(*TaskDeleteRequest)(nil),   // 4: TaskDeleteRequest
	(*TaskCommonResponse)(nil),  // 5: TaskCommonResponse
	(*TasksDetailResponse)(nil), // 6: TasksDetailResponse
}
var file_idl_task_task_proto_depIdxs = []int32{
	0, // 0: TasksDetailResponse.task_detail:type_name -> TaskModel
	1, // 1: TaskService.TaskCreate:input_type -> TaskCreateRequest
	2, // 2: TaskService.TaskUpdate:input_type -> TaskUpdateRequest
	3, // 3: TaskService.TaskShow:input_type -> TaskShowRequest
	4, // 4: TaskService.TaskDelete:input_type -> TaskDeleteRequest
	5, // 5: TaskService.TaskCreate:output_type -> TaskCommonResponse
	5, // 6: TaskService.TaskUpdate:output_type -> TaskCommonResponse
	6, // 7: TaskService.TaskShow:output_type -> TasksDetailResponse
	5, // 8: TaskService.TaskDelete:output_type -> TaskCommonResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_idl_task_task_proto_init() }
func file_idl_task_task_proto_init() {
	if File_idl_task_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_idl_task_task_proto_rawDesc), len(file_idl_task_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_task_task_proto_goTypes,
		DependencyIndexes: file_idl_task_task_proto_depIdxs,
		MessageInfos:      file_idl_task_task_proto_msgTypes,
	}.Build()
	File_idl_task_task_proto = out.File
	file_idl_task_task_proto_goTypes = nil
	file_idl_task_task_proto_depIdxs = nil
}
